const products = [
  // =========================
  // FASHION
  // =========================

  {
    id: 1,
    name: "Premium Cotton Casual T-Shirt",
    category: "fashion",
    price: 699,
    oldPrice: 1199,
    rating: 4.7,
    reviews: 124,
    badge: "Trending",
    image: "/assets/fashionimages/fashion1.jpg",
  },

  {
    id: 2,
    name: "Classic Cotton Crew Neck T-Shirt",
    category: "fashion",
    price: 599,
    oldPrice: 1299,
    rating: 4.5,
    reviews: 89,
    badge: "Popular",
    image: "/assets/fashionimages/fashion2.jpg",
  },

  {
    id: 3,
    name: "Essential Plain Cotton T-Shirt",
    category: "fashion",
    price: 399,
    oldPrice: 1099,
    rating: 4.6,
    reviews: 216,
    badge: "Best Seller",
    image: "/assets/fashionimages/fashion3.jpg",
  },

  {
    id: 4,
    name: "Pure Cotton Comfort T-Shirt",
    category: "fashion",
    price: 319,
    oldPrice: 949,
    rating: 4.4,
    reviews: 76,
    badge: "New",
    image: "/assets/fashionimages/fashion4.jpg",
  },

  {
    id: 5,
    name: "Classic White Cotton T-Shirt",
    category: "fashion",
    price: 649,
    oldPrice: 1099,
    rating: 4.7,
    reviews: 350,
    badge: "Popular",
    image: "/assets/fashionimages/fashion5.jpg",
  },

  {
    id: 6,
    name: "Premium Regular Fit Shirt",
    category: "fashion",
    price: 799,
    oldPrice: 1299,
    rating: 4.7,
    reviews: 359,
    badge: "Trending",
    image: "/assets/fashionimages/fashion6.jpg",
  },

  {
    id: 7,
    name: "Classic Cotton Casual Shirt",
    category: "fashion",
    price: 999,
    oldPrice: 1699,
    rating: 4.7,
    reviews: 318,
    badge: "Popular",
    image: "/assets/fashionimages/fashion7.jpg",
  },

  {
    id: 8,
    name: "Premium Straight Fit Cotton Jeans",
    category: "fashion",
    price: 999,
    oldPrice: 1499,
    rating: 4.7,
    reviews: 318,
    badge: "Trending",
    image: "/assets/fashionimages/fashion8.jpg",
  },

  {
    id: 9,
    name: "Men's Regular Fit Casual Wear",
    category: "fashion",
    price: 329,
    oldPrice: 999,
    rating: 4.7,
    reviews: 318,
    badge: "Popular",
    image: "/assets/fashionimages/fashion9.jpg",
  },

  {
    id: 10,
    name: "Men's Premium Casual Wear",
    category: "fashion",
    price: 339,
    oldPrice: 999,
    rating: 4.7,
    reviews: 318,
    badge: "Trending",
    image: "/assets/fashionimages/fashion10.jpg",
  },

  {
    id: 11,
    name: "Men's Classic Regular Fit Shirt",
    category: "fashion",
    price: 419,
    oldPrice: 989,
    rating: 4.7,
    reviews: 318,
    badge: "Popular",
    image: "/assets/fashionimages/fashion11.jpg",
  },

  {
    id: 12,
    name: "Men's Comfort Regular Fit Shirt",
    category: "fashion",
    price: 318,
    oldPrice: 999,
    rating: 4.7,
    reviews: 318,
    badge: "New",
    image: "/assets/fashionimages/fashion12.jpg",
  },

  {
    id: 13,
    name: "Premium Everyday Casual Wear",
    category: "fashion",
    price: 521,
    oldPrice: 1099,
    rating: 4.7,
    reviews: 318,
    badge: "Trending",
    image: "/assets/fashionimages/fashion13.jpg",
  },

  {
    id: 14,
    name: "Adidas Premium Casual Shoes",
    category: "fashion",
    price: 1099,
    oldPrice: 1599,
    rating: 4.4,
    reviews: 481,
    badge: "Popular",
    image: "/assets/fashionimages/fashion14.jpg",
  },

  // =========================
  // ELECTRONICS
  // =========================

  {
    id: 15,
    name: "Premium Wireless Bluetooth Headphones",
    category: "electronics",
    price: 999,
    oldPrice: 1799,
    rating: 4.3,
    reviews: 61,
    badge: "Popular",
    image: "/assets/electronicsimages/elect1.jpg",
  },

  {
    id: 16,
    name: "Smart Deep Tissue Massage Gun",
    category: "electronics",
    price: 1199,
    oldPrice: 1999,
    rating: 4.4,
    reviews: 98,
    badge: "Trending",
    image: "/assets/electronicsimages/elect2.jpg",
  },

  {
    id: 17,
    name: "Philips Portable FM Radio",
    category: "electronics",
    price: 1999,
    oldPrice: 3449,
    rating: 4.6,
    reviews: 98,
    badge: "Popular",
    image: "/assets/electronicsimages/elect3.jpg",
  },

  {
    id: 18,
    name: "Digital Hot Air Fryer",
    category: "electronics",
    price: 3899,
    oldPrice: 4499,
    rating: 4.7,
    reviews: 98,
    badge: "Best Seller",
    image: "/assets/electronicsimages/elect4.jpg",
  },

  {
    id: 19,
    name: "Samsung Galaxy Z Fold Smartphone",
    category: "electronics",
    price: 150000,
    oldPrice: 199999,
    rating: 4.8,
    reviews: 98,
    badge: "Premium",
    image: "/assets/electronicsimages/elect5.jpg",
  },

  {
    id: 20,
    name: "Google Pixel 7 Smartphone",
    category: "electronics",
    price: 66999,
    oldPrice: 71999,
    rating: 4.2,
    reviews: 98,
    badge: "Popular",
    image: "/assets/electronicsimages/elect6.jpg",
  },

  {
    id: 21,
    name: "HP Ultra Performance Laptop",
    category: "electronics",
    price: 59999,
    oldPrice: 67999,
    rating: 4.5,
    reviews: 278,
    badge: "Trending",
    image: "/assets/electronicsimages/elect7.jpg",
  },

  {
    id: 22,
    name: "Apple MacBook Pro Laptop",
    category: "electronics",
    price: 255000,
    oldPrice: 265000,
    rating: 4.9,
    reviews: 400,
    badge: "Premium",
    image: "/assets/electronicsimages/elect8.jpg",
  },

  {
    id: 23,
    name: "boAt Premium Bluetooth Speaker",
    category: "electronics",
    price: 8999,
    oldPrice: 10999,
    rating: 4.3,
    reviews: 498,
    badge: "Popular",
    image: "/assets/electronicsimages/elect9.jpg",
  },

  {
    id: 24,
    name: "JBL Pro Wireless Bluetooth Speaker",
    category: "electronics",
    price: 999,
    oldPrice: 1999,
    rating: 4.4,
    reviews: 529,
    badge: "Best Seller",
    image: "/assets/electronicsimages/elect10.jpg",
  },

  {
    id: 25,
    name: "Apple iPad Pro A16",
    category: "electronics",
    price: 59999,
    oldPrice: 70000,
    rating: 4.4,
    reviews: 578,
    badge: "Popular",
    image: "/assets/electronicsimages/elect11.jpg",
  },

  {
    id: 26,
    name: "Apple iPad Pro A12",
    category: "electronics",
    price: 99999,
    oldPrice: 110999,
    rating: 4.4,
    reviews: 98,
    badge: "Premium",
    image: "/assets/electronicsimages/elect12.jpg",
  },
];

export default products;