const One2 = [
  // ==========================================
  // GROCERY
  // ==========================================

  {
    id: 54,
    name: "Premium Basmati Rice",
    category: "grocery",
    price: 599,
    oldPrice: 699,
    rating: 4.6,
    reviews: 324,
    badge: "Popular",
    image: "/assets/grocery/g1.jpg",
  },

  {
    id: 55,
    name: "Pure Organic Cooking Oil",
    category: "grocery",
    price: 799,
    oldPrice: 899,
    rating: 4.5,
    reviews: 218,
    badge: "Best Seller",
    image: "/assets/grocery/g2.jpg",
  },

  {
    id: 56,
    name: "Premium Almonds",
    category: "grocery",
    price: 999,
    oldPrice: 1199,
    rating: 4.7,
    reviews: 486,
    badge: "Premium",
    image: "/assets/grocery/g4.jpg",
  },

  {
    id: 57,
    name: "Fresh & Natural Organic Honey",
    category: "grocery",
    price: 499,
    oldPrice: 599,
    rating: 4.6,
    reviews: 392,
    badge: "Organic",
    image: "/assets/grocery/g3.jpg",
  },

  {
    id: 58,
    name: "Fresh Organic Tomatoes",
    category: "grocery",
    price: 139,
    oldPrice: 269,
    rating: 4.3,
    reviews: 185,
    badge: "Fresh",
    image: "/assets/grocery/g5.jpg",
  },

  {
    id: 59,
    name: "Fresh & Organic Kidney Beans",
    category: "grocery",
    price: 499,
    oldPrice: 599,
    rating: 4.4,
    reviews: 176,
    badge: "Organic",
    image: "/assets/grocery/g6.jpg",
  },

  {
    id: 60,
    name: "Organic Red-Chilli Powder",
    category: "grocery",
    price: 199,
    oldPrice: 299,
    rating: 4.5,
    reviews: 142,
    badge: "Fresh",
    image: "/assets/grocery/g7.jpg",
  },

  {
    id: 61,
    name: "Fresh Madhur Sugar Packet",
    category: "grocery",
    price: 249,
    oldPrice: 499,
    rating: 4.4,
    reviews: 219,
    badge: "Popular",
    image: "/assets/grocery/g8.jpg",
  },

  {
    id: 62,
    name: "Fresh & Premium Cashew",
    category: "grocery",
    price: 449,
    oldPrice: 599,
    rating: 4.6,
    reviews: 267,
    badge: "Healthy",
    image: "/assets/grocery/g9.jpg",
  },

  {
    id: 63,
    name: "Premium Dry Fruits Collection",
    category: "grocery",
    price: 699,
    oldPrice: 899,
    rating: 4.7,
    reviews: 381,
    badge: "Premium",
    image: "/assets/grocery/g10.jpg",
  },

  {
    id: 64,
    name: "TATA DESH KA NAMAK",
    category: "grocery",
    price: 20,
    oldPrice: 25,
    rating: 4.4,
    reviews: 193,
    badge: "Fresh",
    image: "/assets/grocery/g11.jpg",
  },

  {
    id: 65,
    name: "Fresh Mix Daal From Neelam",
    category: "grocery",
    price: 349,
    oldPrice: 499,
    rating: 4.5,
    reviews: 246,
    badge: "Trending",
    image: "/assets/grocery/g12.jpg",
  },

  {
    id: 66,
    name: "Organic Yeeloe Moong Daal",
    category: "grocery",
    price: 199,
    oldPrice: 239,
    rating: 4.6,
    reviews: 312,
    badge: "Combo",
    image: "/assets/grocery/g13.jpg",
  },

  // ==========================================
  // SPORTS
  // ==========================================

  {
    id: 67,
    name: "NIVIA Storm Football",
    category: "sports",
    price: 299,
    oldPrice: 459,
    rating: 4.5,
    reviews: 248,
    badge: "Popular",
    image: "/assets/sports/s1.jpg",
  },

  {
    id: 68,
    name: "Premium Volleyball Net",
    category: "sports",
    price: 1099,
    oldPrice: 1399,
    rating: 4.2,
    reviews: 126,
    badge: "Sports Pick",
    image: "/assets/sports/s2.jpg",
  },

  {
    id: 69,
    name: "NIVIA Shin Guard Protection",
    category: "sports",
    price: 199,
    oldPrice: 289,
    rating: 4.1,
    reviews: 184,
    badge: "Popular",
    image: "/assets/sports/s3.jpg",
  },

  {
    id: 70,
    name: "NIVIA Football Goalkeeper Gloves",
    category: "sports",
    price: 459,
    oldPrice: 769,
    rating: 4.0,
    reviews: 156,
    badge: "Trending",
    image: "/assets/sports/s4.jpg",
  },

  {
    id: 71,
    name: "Badminton Racket With Shuttle Set",
    category: "sports",
    price: 299,
    oldPrice: 569,
    rating: 4.2,
    reviews: 237,
    badge: "Best Seller",
    image: "/assets/sports/s5.jpg",
  },

  {
    id: 72,
    name: "NIVIA Premium Volleyball",
    category: "sports",
    price: 789,
    oldPrice: 1099,
    rating: 4.3,
    reviews: 174,
    badge: "Popular",
    image: "/assets/sports/s6.jpg",
  },

  {
    id: 73,
    name: "LEDPARO Premium Bicycle",
    category: "sports",
    price: 7989,
    oldPrice: 10988,
    rating: 4.5,
    reviews: 89,
    badge: "Premium",
    image: "/assets/sports/s7.jpg",
  },

  {
    id: 74,
    name: "MRF Wooden Cricket Bat",
    category: "sports",
    price: 1489,
    oldPrice: 3889,
    rating: 4.2,
    reviews: 428,
    badge: "Best Seller",
    image: "/assets/sports/s8.jpg",
  },

  {
    id: 75,
    name: "PRIME Plastic Cricket Bat",
    category: "sports",
    price: 679,
    oldPrice: 998,
    rating: 4.5,
    reviews: 216,
    badge: "Popular",
    image: "/assets/sports/s9.jpg",
  },

  {
    id: 76,
    name: "Heavy Duty Practice Cricket Ball",
    category: "sports",
    price: 349,
    oldPrice: 588,
    rating: 4.0,
    reviews: 143,
    badge: "Practice",
    image: "/assets/sports/s10.jpg",
  },

  {
    id: 77,
    name: "Premium Leg Guards",
    category: "sports",
    price: 989,
    oldPrice: 1388,
    rating: 4.3,
    reviews: 194,
    badge: "Protection",
    image: "/assets/sports/s11.jpg",
  },

  {
    id: 78,
    name: "Professional Sports Training Equipment",
    category: "sports",
    price: 1299,
    oldPrice: 1799,
    rating: 4.4,
    reviews: 137,
    badge: "Trending",
    image: "/assets/sports/s12.jpg",
  },

  {
    id: 79,
    name: "Premium Running & Jogging Shoes",
    category: "sports",
    price: 1659,
    oldPrice: 2988,
    rating: 4.5,
    reviews: 368,
    badge: "Best Seller",
    image: "/assets/sports/s13.jpg",
  },

  {
    id: 80,
    name: "Nike Mercurial Football Shoes",
    category: "sports",
    price: 3549,
    oldPrice: 4989,
    rating: 4.7,
    reviews: 524,
    badge: "Premium",
    image: "/assets/sports/s14.jpg",
  },

  {
    id: 81,
    name: "Affordable Vector Football Shoes",
    category: "sports",
    price: 899,
    oldPrice: 1299,
    rating: 4.6,
    reviews: 287,
    badge: "Trending",
    image: "/assets/sports/s15.jpg",
  },
];

export default One2;
