// One3.js

const products = [
  // ========================================
  // TOYS & KIDS
  // ========================================

  {
    id: 82,
    name: "Cute Plush Puppy Soft Toy",
    image: "/assets/toys/t1.jpg",
    price: 399,
    oldPrice: 799,
    discount: "25% OFF",
    category: "toys-kids",
    rating: 4.7,
    reviews: 248,
    badge: "Popular",
  },

  {
    id: 83,
    name: "Interactive Musical Telephone Toy Car",
    image: "/assets/toys/t2.jpg",
    price: 699,
    oldPrice: 999,
    discount: "30% OFF",
    category: "toys-kids",
    rating: 4.5,
    reviews: 164,
    badge: "Kids Pick",
  },

  {
    id: 84,
    name: "Kids Remote Control Off-Road Jeep",
    image: "/assets/toys/t3.jpg",
    price: 1499,
    oldPrice: 2499,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.6,
    reviews: 187,
    badge: "Trending",
  },

  {
    id: 85,
    name: "Kids Electric Ride-On Scooter",
    image: "/assets/toys/t4.jpg",
    price: 4999,
    oldPrice: 6999,
    discount: "29% OFF",
    category: "toys-kids",
    rating: 4.5,
    reviews: 96,
    badge: "Popular",
  },

  {
    id: 86,
    name: "Kids Electric Sports Bike",
    image: "/assets/toys/t5.jpg",
    price: 5499,
    oldPrice: 7999,
    discount: "31% OFF",
    category: "toys-kids",
    rating: 4.7,
    reviews: 142,
    badge: "Best Seller",
  },

  {
    id: 87,
    name: "Kids 3-Wheel Safety Scooter",
    image: "/assets/toys/t6.jpg",
    price: 899,
    oldPrice: 1499,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.6,
    reviews: 219,
    badge: "Popular",
  },

  {
    id: 88,
    name: "Colorful Ring Stacking Toy",
    image: "/assets/toys/t7.jpg",
    price: 349,
    oldPrice: 599,
    discount: "42% OFF",
    category: "toys-kids",
    rating: 4.4,
    reviews: 173,
    badge: "Learning",
  },

  {
    id: 89,
    name: "Interactive Dancing Robot Toy",
    image: "/assets/toys/t8.jpg",
    price: 799,
    oldPrice: 1299,
    discount: "38% OFF",
    category: "toys-kids",
    rating: 4.5,
    reviews: 128,
    badge: "Trending",
  },

  {
    id: 90,
    name: "Colorful Creative Linking Beads Set",
    image: "/assets/toys/t9.jpg",
    price: 299,
    oldPrice: 499,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.6,
    reviews: 194,
    badge: "Creative",
  },

  {
    id: 91,
    name: "Kids Toy Blaster Gun with Foam Darts",
    image: "/assets/toys/t10.jpg",
    price: 599,
    oldPrice: 999,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.4,
    reviews: 157,
    badge: "Fun",
  },

  {
    id: 92,
    name: "Kids Digital Camera with USB Cable",
    image: "/assets/toys/t11.jpg",
    price: 899,
    oldPrice: 1499,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.5,
    reviews: 236,
    badge: "New",
  },

  {
    id: 93,
    name: "Best Plastic Sitting Car For Kids Drive",
    image: "/assets/toys/t12.jpg",
    price: 899,
    oldPrice: 1499,
    discount: "40% OFF",
    category: "toys-kids",
    rating: 4.5,
    reviews: 236,
    badge: "New",
  },

  // ========================================
  // BOOKS & INSTRUMENTS
  // ========================================

  {
    id: 94,
    name: "The Psychology of Money",
    image: "/assets/book-instrument/b4.jpg",
    price: 399,
    oldPrice: 499,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.8,
    reviews: 542,
    badge: "Bestseller",
  },

  {
    id: 95,
    name: "Traditional Tabla Set",
    image: "/assets/book-instrument/i2.jpg",
    price: 889,
    oldPrice: 1289,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.5,
    reviews: 522,
    badge: "Basic",
  },

  {
    id: 96,
    name: "Zero to One",
    image: "/assets/book-instrument/b3.jpg",
    price: 349,
    oldPrice: 499,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.4,
    reviews: 632,
    badge: "Trending",
  },

  {
    id: 97,
    name: "Acoustic Guitar with Bag & Accessories",
    image: "/assets/book-instrument/i1.jpg",
    price: 2799,
    oldPrice: 2999,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.6,
    reviews: 352,
    badge: "Popular",
  },

  {
    id: 98,
    name: "Traditional Indian Sitar",
    image: "/assets/book-instrument/i4.jpg",
    price: 349,
    oldPrice: 499,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.2,
    reviews: 6222,
    badge: "Trending",
  },

  {
    id: 99,
    name: "Dreams from My Father - Barack Obama",
    image: "/assets/book-instrument/b2.jpg",
    price: 349,
    oldPrice: 499,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.1,
    reviews: 582,
    badge: "Trending",
  },

  {
    id: 100,
    name: "Premium Tabla Set",
    image: "/assets/book-instrument/i3.jpg",
    price: 999,
    oldPrice: 1699,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.3,
    reviews: 832,
    badge: "Trending",
  },

  {
    id: 101,
    name: "Rich Dad Poor Dad",
    image: "/assets/book-instrument/b1.jpg",
    price: 879,
    oldPrice: 999,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.6,
    reviews: 892,
    badge: "Trending",
  },

  {
    id: 102,
    name: "Digital Piano Keyboard",
    image: "/assets/book-instrument/i6.jpg",
    price: 2249,
    oldPrice: 2799,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.5,
    reviews: 972,
    badge: "Trending",
  },

  {
    id: 103,
    name: "Trumpet Musical Instrument",
    image: "/assets/book-instrument/i5.jpg",
    price: 349,
    oldPrice: 499,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.4,
    reviews: 542,
    badge: "Trending",
  },

  {
    id: 104,
    name: "Secrets of the Titanic",
    image: "/assets/book-instrument/b5.jpg",
    price: 789,
    oldPrice: 999,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.4,
    reviews: 582,
    badge: "Trending",
  },

  {
    id: 105,
    name: "The Art of Silent Healing",
    image: "/assets/book-instrument/b6.jpg",
    price: 499,
    oldPrice: 799,
    discount: "20% OFF",
    category: "books-instruments",
    rating: 4.2,
    reviews: 542,
    badge: "Trending",
  },
];

export default products;
